### ISSUE TITLE
Customer Profile NOT accessible

### ISSUE THREAD

**Issue by markramel** [VirtoCommerce/vc-storefront-deprecated#72] opened 2018-04-25 06:08 UTC
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Chrome Version 65.0.3325.181 
- Platform version: Community License 2.13.21
- Storefront version: 

### Steps to reproduce
1. create an account
2. login with the new account
3. manage profile to update address

**Comment by markramel** [comment] 2018-04-28 15:19
It seems to have the same  scenario in your demo site. I can't manage my address after creating an account.      Where can we look on this at the platform to debug this?

**Comment by tatarincev** [comment] 2019-12-26 13:31
Can't reproduce on the current demo.
You may reopen this issue if it has been closed in error.

**Closed as completed by tatarincev** 2019-12-26 13:31 UTC
